// This file is generated by Slice Machine. Update with care!

import Button from './Button';
import Link from './Link';
import Menu from './Menu';
import Paragraph from './Paragraph';
import Title from './Title';

export { Button, Link, Menu, Paragraph, Title };

export const components = {
    button: Button,
    link: Link,
    menu: Menu,
    paragraph: Paragraph,
    title: Title,
};
