// This file is generated by Slice Machine. Update with care!

import FooterButton from './FooterButton';
import NavigationButton from './NavigationButton';
import NavigationLink from './NavigationLink';
import NavigationMenu from './NavigationMenu';
import Paragraph from './Paragraph';
import Title from './Title';

export {
    FooterButton,
    NavigationButton,
    NavigationLink,
    NavigationMenu,
    Paragraph,
    Title,
};

export const components = {
    footer_button: FooterButton,
    navigation_button: NavigationButton,
    navigation_link: NavigationLink,
    navigation_menu: NavigationMenu,
    paragraph: Paragraph,
    title: Title,
};
